In [3]:
import numpy as np # 最好是标准导入方式
my_arr = np.arange(1000000)
my_list = list(range(1000000))

# 运行时间
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 67.9 ms


In [4]:
%time for _ in range(10): my_list2 = my_list * 2

Wall time: 419 ms


In [5]:
# NumPy ndarray: 多维数组对象
data = np.random.randn(2, 3)
data

array([[-0.51142246, -1.0857652 , -2.54269722],
       [ 0.25880438, -0.88431366, -0.76061138]])

In [6]:
data * 10

array([[ -5.11422458, -10.85765203, -25.42697224],
       [  2.58804382,  -8.84313658,  -7.60611375]])

In [7]:
data + data

array([[-1.02284492, -2.17153041, -5.08539445],
       [ 0.51760876, -1.76862732, -1.52122275]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
# 生成ndarray
data1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
data2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
arr2 = np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
# 检查为多少维数组
arr1.ndim

1

In [14]:
arr2.ndim

2

In [15]:
arr2.shape # 几行几列

(2, 5)

In [16]:
arr1.dtype

dtype('int32')

In [17]:
np.zeros(10) # 全零数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2)) # 没有初始化的数组

array([[[1.06978045e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.21472101e+160]],

       [[3.09059059e-057, 2.38333949e+180],
        [9.34285913e+164, 8.38272344e+165],
        [1.62030347e-051, 4.75473300e+174]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
mydata = [1, 2, 3]
mynddata = np.asarray(mydata)
mynddata

array([1, 2, 3])

In [26]:
mynddata1 = np.asarray(mynddata) # mynddata已经为ndarray 则不再复制，所以两者地址一致
id(mynddata1)

2165356638736

In [27]:
id(mynddata)

2165356638736

In [29]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # 设置类型
arr2= np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
# astype显式地转换数组
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [32]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [33]:
arr = np.array([1.1, 2.2, 3.314])
arr

array([1.1  , 2.2  , 3.314])

In [35]:
arr.astype(np.int32) # 浮点型转换为整数型

array([1, 2, 3])

In [36]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [39]:
# NumPy数组算术
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [41]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [43]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [44]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [45]:
# 基础索引与切片
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [49]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345    #改变arr_slice原数组arr也会改变
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [54]:
arr_slice[:] = 64   #数组arr_slice全部改变
arr_slice1 = arr[5:8].copy()
arr_slice1

array([64, 64, 64])

In [55]:
id(arr_slice)

2165269455776

In [56]:
id(arr_slice1)

2165269457376

In [53]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])